INSERT INTO products (
    id,
    seller_id,
    name,
    thumbnail_url,
    description,
    parent_category_id,
    parent_category_name,
    category_id,
    category_name,
    starting_price,
    current_price,
    buy_now_price,
    step_price,
    created_at,
    end_at,
    auto_extend,
    bid_count,
    current_bidder,
    order_created,
    sent_email
) VALUES

-- ================= PRODUCT 1 (EXPIRED, HAS WINNER) =================
(
    1,
    10,
    'Vintage Mechanical Watch',
    'https://example.com/thumb/watch.jpg',
    'Classic vintage mechanical watch in good condition.',
    1, 'Accessories',
    4, 'Watches',
    100.0,
    180.0,
    300.0,
    10.0,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '1 hour',
    false,
    5,
    7,
    false,
    false
),

-- ================= PRODUCT 2 (EXPIRED, HAS WINNER) =================
(
    2,
    11,
    'Gaming Mechanical Keyboard',
    'https://example.com/thumb/keyboard.jpg',
    'RGB mechanical keyboard, lightly used.',
    2, 'Electronics',
    7, 'Computer Accessories',
    50.0,
    95.0,
    150.0,
    5.0,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '30 minutes',
    true,
    8,
    8,
    false,
    false
),

-- ================= PRODUCT 3 (EXPIRED, NO BID) =================
(
    3,
    10,
    'Handmade Leather Wallet',
    'https://example.com/thumb/wallet.jpg',
    'Handcrafted leather wallet, brand new.',
    1, 'Fashion',
    5, 'Wallets',
    40.0,
    NULL,
    80.0,
    5.0,
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '10 minutes',
    false,
    0,
    NULL,
    false,
    false
),

-- ================= PRODUCT 4 (NOT EXPIRED YET) =================
(
    4,
    11,
    'Wireless Noise Cancelling Headphones',
    'https://example.com/thumb/headphones.jpg',
    'Premium wireless headphones with ANC.',
    2, 'Electronics',
    8, 'Audio',
    200.0,
    230.0,
    350.0,
    10.0,
    NOW() - INTERVAL '5 hours',
    NOW() + INTERVAL '2 hours',
    true,
    3,
    9,
    false,
    false
),

-- ================= PRODUCT 5 (EXPIRED, HAS WINNER) =================
(
    5,
    10,
    'Limited Edition Sneakers',
    'https://example.com/thumb/sneakers.jpg',
    'Limited edition sneakers, never worn.',
    1, 'Fashion',
    6, 'Shoes',
    120.0,
    210.0,
    300.0,
    10.0,
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '2 hours',
    false,
    6,
    9,
    false,
    false
);
