export const endpoints = {
  auth: {
    register: '/auth/register',
    verifyOtp: '/auth/verify-otp',
    signIn: '/auth/sign-in',
    signInGoogle: '/auth/sign-in/google',
    validateJwt: '/auth/validate-jwt',
  },
  users: {
    profile: '/users/profile/me',
    simple: (email: string) => `/users/simple?email=${email}`,
    simpleById: (id: number) => `/users/${id}/simple`,
    search: '/users/search',
    upgradeToSeller: (reason: string) => `/users/upgrade-to-seller?reason=${encodeURIComponent(reason)}`,
    approveUpgrade: (requestId: number) => `/users/${requestId}/approve`,
    upgradeRequests: '/users',
    verifyEmail: '/users/verify-email',
    deleteUser: '/users',
  },
  categories: {
    list: '/categories',
    create: '/categories',
    detail: (id: number) => `/categories/${id}`,
    update: (id: number) => `/categories/${id}`,
    delete: (id: number) => `/categories/${id}`,
    byParent: (parentId: number) => `/categories/parent/${parentId}`,
  },
  products: {
    create: '/products',
    list: '/products',
    search: '/products/search',
    detail: (id: number) => `/products/${id}`,
    update: (id: number) => `/products/${id}`,
    delete: (id: number) => `/products/${id}`,
    updateDescription: (id: number) => `/products/${id}/description`,
    bySeller: (sellerId: number) => `/products/seller/${sellerId}`,
    topEnding: '/products/top-ending',
    topMostBids: '/products/top-most-bids',
    topHighestPrice: '/products/top-highest-price',
  },
  bids: {
    place: '/bids',
    search: '/bids/search',
  },
  orders: {
    create: '/orders/data/product/',
    list: '/orders/data/product/',
    detail: (id: number) => `/orders/data/product/${id}`,
    pay: (id: number) => `/orders/data/product/${id}/pay`,
    shippingAddress: (id: number) => `/orders/data/product/${id}/shipping-address`,
    shippingInvoice: (id: number) => `/orders/data/product/${id}/shipping-invoice`,
    confirmDelivery: (id: number) => `/orders/data/product/${id}/confirm-delivery`,
    cancel: (id: number) => `/orders/data/product/${id}/cancel`,
    sendMessage: (id: number) => `/orders/data/product/${id}/messages`,
    getMessages: (id: number) => `/orders/data/product/${id}/messages`,
    rate: (id: number) => `/orders/data/product/${id}/rate`,
    getRating: (id: number) => `/orders/data/product/${id}/rating`,
    getUserRating: (userId: number) => `/orders/data/users/${userId}/rating`,
    adminOrders: '/orders/data/admin/orders',
    websocket: '/order-websocket/',
  },
  watchlist: {
    list: '/watchlist',
    add: (productId: number) => `/watchlist/${productId}`,
    remove: (productId: number) => `/watchlist/${productId}`,
    check: (productId: number) => `/watchlist/check/${productId}`,
  },
  comments: {
    history: (productId: number) => `/comments/history/products/${productId}`,
    websocket: '/comments/websocket/abc',
  },
  media: {
    upload: '/media/upload',
    uploadMultiple: '/media/upload/multiple',
    presign: '/media/presign',
  },
  notifications: {
    sendEmail: '/notifications/email',
  },
};
